### ISSUE TITLE
After installation of OpenSSH SSH Client stucks at loading process.

### ISSUE THREAD

**Issue by arinc9** [Sticktron/g0blin#157] opened 2018-01-29 14:59 UTC

**Comment by Sticktron** [comment] 2018-01-30 19:02
Can you provide more detail? I don't understand you question.

This doesn't work? (use your own IP address)
`
ssh root@192.168.0.69
`

**Comment by arinc9** [comment] 2018-01-30 19:15
Not getting "not permitted", it actually finds the connection port but stucks after entering the command. Stucks while connecting.

**Comment by KeyFlyz** [comment] 2018-01-31 00:07
OpenSSH doesn't work for me it says connection refused but I can reinstall dropbear and it works only problem is when I reboot it uninstalls dropbear and I have to reinstall it hopefully the next release will not auto uninstall dropbear were we can use which ever one we want. G0blin RC2 iPhone 6 10.3.1.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ringosham** [comment] 2018-01-31 01:11
Confirmed not working. Not even ssh-ing to itself works.
On OpenSSH, the terminal stuck after entering the command.
On DropbearSSH, connection refused.
iPad mini 2, iOS 10.3.1

**Comment by arinc9** [comment] 2018-01-31 08:50
@KeyFlyz use my fork. I've removed the line which deletes dropbear on every rejailbreak.

**Comment by KeyFlyz** [comment] 2018-01-31 14:15
@arinc9 Thank You for the offer but I don't use any IPAs other than the official one unless I compile & fix them myself which I don't have access to a mac right now so I won't be doing that. I just need it fixed on RC3 where it doesn't do that.

**Comment by arinc9** [comment] 2018-01-31 14:26
It's open source, if you think I've compiled something different than the source, it's not. It's not a fix, @sticktron made it on purpose to remove dropbear if you're coming from RC1. I understand you don't trust ipas coming from nowhere so check the commits I've done in my fork if you wanna learn.

**Comment by KeyFlyz** [comment] 2018-01-31 18:14
Maybe fix wasn't the right word to use maybe I should've used adjust...😂😂😂

**Comment by resistor4u** [comment] 2018-02-05 08:47
iphone 6s on 10.3.2 using the rc2 and NewTerm2. i'm confirming part of ssh problems. i cannot remotely log into the device, nor can i login from the device itself. however, i can ssh from the phone to my laptop and to other devices. doing a portscan shows that the phone's port 22 is open for ssh.

**Comment by resistor4u** [comment] 2018-02-06 18:59
I'm not a networking supersaiyan, but I'm eager to fix this myself if possible. Changing the source code and recompiling the .ipa is not an option, because I'm on osx 10.11.6 and the required xcode isn't available without upgrading to 10.12.

Phoneside, I added `AllowUsers root mobile` to /etc/ssh/sshd_config just to be sure. Although the openssh daemon exists, stopping and starting the service with `launchctl` didn't have an effect. Passing `-vvv` from the local machine shows that ssh indeed successfully connects to port 22, but hangs right before reaching `debug1: SSH2_MSG_KEXINIT` stages. The iphone logs in `/private/var/logs/CrashReporter/com.openssh.sshd.****` return:
```
Daemon/Service Name:	com.openssh.sshd.****
OS Version:		14F89
Hardware Model:		N71AP

This daemon/service is not allowed to execute.
```
Also, I get the same results when trying to ssh to the phone via `iproxy 2222 22` then in separate term `ssh mobile@localhost -p 2222`. Finally, and most vexingly, I am able to connect to the iphone in from the mac Finder > Go > Connect to Server... when providing port 11111 e.g., `http://192.168.1.128:11111/`.

Maybe there is an obvious fix here, but I've exhausted my knowledge short of recompiling the ipa. @Sticktron ideas?

**Comment by arinc9** [comment] 2018-02-06 19:07
So, did you have connection succesfully when you added AllowUsers root mobile and does it only work if you set the port to 11111?

**Comment by resistor4u** [comment] 2018-02-06 19:18
Since AllowUsers is in the ssh_config file, I wouldn't expect anything outside ssh to pick up on this. The mac finder option is thru Filza, which allows WebDAV.

**Comment by Sticktron** [comment] 2018-02-08 12:54
When you install OpenSSH it is set to use port 22. That port won't work from apps on the device itself.
If you want to change the port you can search for the procedure on google. It involves adding a new service to /etc/services or modifying the existing ssh entry.

**Closed by Sticktron** 2018-02-08 12:54 UTC
Labels: need feedback

**Comment by resistor4u** [comment] 2018-02-09 04:01
> When you install OpenSSH it is set to use port 22. That port won't work from apps on the device itself.
@Sticktron If this is the case, then how am I able to ssh *from* my iphone *to* my laptop?

I've manually changed the port twice, from 22 to 50000 and to 50505, but neither worked. In `/etc/services` I changed
```
ssh              22/udp     # SSH Remote Login Protocol
ssh              22/tcp     # SSH Remote Login Protocol
```
to
```
ssh              50000/udp     # SSH Remote Login Protocol
ssh              50000/tcp     # SSH Remote Login Protocol
```
Then in `/Library/LaunchDaemons/com.openssh.sshd.plist` I changed the listener key from `<string>ssh</string>` to `<string>50000</string>`. (I renamed the original file to `/Library/LaunchDaemons/com.openssh.sshd.plist.bak`.) Then I unloaded and loaded the plist service.

After all this, trying to ssh from my laptop specifying port 50000 shows I'm hanging at the same spot. And when I ssh from the phone to the laptop, I get rejected on port 50000. So when I specify port 22 to reach the laptop, I connect no problem... So, I'm getting the same behavior on the default port 22 as I am on any other. @Sticktron is this different for you?

**Comment by Sticktron** [comment] 2018-02-09 05:29
I was referring to local SSH connections from an App. Apple blocks them from using port 22.

Don't change the listener name unless you also add a corresponding entry to the services list.  You can add a second entry called ssh2 for example, and then change OpenSSH's listener to ssh2.

**Comment by resistor4u** [comment] 2018-02-09 05:50
I've added an separate, additional `com.openssh.sshd2.plist`, load and unload, and resprung, but no luck. The only step I've not yet tried is hard rebooting. But unloading, loading, and starting the service means I don't really need to reboot, right?

**Comment by Sticktron** [comment] 2018-02-09 05:53
You can't start OpenSSH on iOS 10 by using it's launchdaemon. I start it manually during the jailbreak.

This is fine (provided nothing else is on port 50000)
`
ssh              50000/udp     # SSH Remote Login Protocol
ssh              50000/tcp     # SSH Remote Login Protocol
`

Leave the plist the way it was originally. I'm not sure if you have to reboot for changes to /etc/services to take effect.

**Comment by resistor4u** [comment] 2018-02-09 06:04
i successfully add the 2nd plist to launchd. but my logs show
```
Daemon/Service Name:	com.openssh.sshd.E27F5918-A487-4430-848A-9C27B7E495B9
OS Version:		14F89
Hardware Model:		N71AP


This daemon/service is not allowed to execute.
```
i'm going to reboot and see what happens.

**Comment by resistor4u** [comment] 2018-02-09 07:00
ok well this is uber frustrating. from my experience, it just doesn't seem like you can get it working short of having a g0blin binary that does *not* unload openssh during the jailbreak. but that's maybe because it's late and i'm tired, but man i've tried all i can think of.

**Comment by resistor4u** [comment] 2018-02-09 17:57
Rebooted and jailbreak no problem, and all changes outlined above are persistent, but still the same behavior. So there's that.

FWIW, running netstat on the phone while trying to ssh from the laptop shows that there's a port connection established (more specifically, it's of the kind:
```
tcp4    21    0    192.168.1.128.ssh2    192.168.1.134.63514    ESTABLISHED
tcp4    21    0    192.168.1.128.ssh    192.168.1.134.63476    CLOSE_WAIT
tcp4    21    0    192.168.1.128.ssh2    192.168.1.134.63473    CLOSE_WAIT
tcp4    21    0    192.168.1.128.ssh    192.168.1.134.63472    CLOSE_WAIT
```
@Sticktron could you please confirm that the ssh you have on your phone allows you to ssh from your phone to another device *and* from a separate device to your phone? Also, are you using your rc1 or rc2 ipa?

**Comment by resistor4u** [comment] 2018-02-16 07:27
I capitulated and changed some values in the xcode storyboards. Compiling & jb no problem. All three -- ssh, sftp, and scp -- work correctly for me now.

**Comment by arinc9** [comment] 2018-02-16 09:23
Wanna add it as a pull request?

**Comment by resistor4u** [comment] 2018-02-28 18:06
@arinc9 done. but as a followup, i note that this is really on-again, off-again. i can't find any consistency or pattern behind this working or not working; it's just, sometimes yes, sometimes no :-\
